language: crystal
script: "shards update && make spec"
before_deploy: make release
deploy:
  provider: releases
  api_key:
    secure: VPNhmZR0qN7bZKcjA0BhtwaWpqlbMZWvtwYoUkqUdBE9tDG4c8llGrVRTk5Xd6RX5rPoWcR0JY+tq3vdIkVvlIW2pH/iMdwlIHapEtYOLpVTGQ3ikknLcqsR/EcOxUZxBNQCFiVDnC3Pn3vfLzpLLhCsTUkEq8RQLmjISjZnJ3E=
  file: "*.zip"
  file_glob: true
  on:
    tags: true
sudo: required
before_install: |
  curl -sL https://github.com/ysbaddaden/shards/releases/latest | \
  egrep -o '/ysbaddaden/shards/releases/download/v[0-9\.]*/shards.*linux_amd64.tar.gz' | \
  wget --base=http://github.com/ -i - -O - | \
  sudo tar xz -C /usr/local/bin
